### ISSUE TITLE
Validator makes no distinction of defined vs undefined

### ISSUE THREAD

**Issue by tannerlinsley** [jsonmaur/litespeed#6]
Here https://github.com/jsonmaur/litespeed/blob/master/src/validation.js#L21, we are checking the value to see if it's truthy, but wouldn't sending a `false` boolean throw this off?  

I feel like we should be checking to see if the value is `undefined`.  Even in some scenarios, you may want to deliberately pass an empty string or `null` to PATCH a record in the database. 

Thoughts?

**Comment by jsonmaur** [comment]
Yeah, agreed. I would just do something like
```
const isUndefined = val === undefined
```
And replace the two instances of `!val` with `isUndefined`. You can just add this to your current pull request.

**Comment by tannerlinsley** [comment]
K
